services:
  sb_app:
    container_name: totospizza-eshop
    image: totospizza-eshop:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      pg_db:
        condition: service_healthy
  pg_db:
    container_name: totospz_db
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "totospzdb", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5