api:
    security:
        expiration: 60
        secret: ${JWT_SECRET}
server:
    error:
        include-stacktrace: never
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: validate
        show-sql: false
