CREATE TABLE cliente
(
    cli_cod     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usu_reg     INTEGER                                  NOT NULL,
    usu_mod     INTEGER                                  NOT NULL,
    fec_hor_reg TIMESTAMP with time zone                 NOT NULL,
    fec_hor_mod TIMESTAMP with time zone                 NOT NULL,
    cli_per_cod INTEGER                                  NOT NULL,
    cli_ruc     CHAR(11),
    cli_est     VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (cli_cod)
);

CREATE TABLE perfiles
(
    perf_cod    INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL,
    usu_reg     INTEGER                                  NOT NULL,
    usu_mod     INTEGER                                  NOT NULL,
    fec_hor_reg TIMESTAMP with time zone                 NOT NULL,
    fec_hor_mod TIMESTAMP with time zone                 NOT NULL,
    perf_nom    VARCHAR(25)                              NOT NULL,
    perf_des    VARCHAR(128)                             NOT NULL,
    perf_est    VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_perfiles PRIMARY KEY (perf_cod)
);

CREATE TABLE personas
(
    per_cod     INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL,
    usu_reg     INTEGER                                  NOT NULL,
    usu_mod     INTEGER                                  NOT NULL,
    fec_hor_reg TIMESTAMP with time zone                 NOT NULL,
    fec_hor_mod TIMESTAMP with time zone                 NOT NULL,
    per_nom     VARCHAR(120)                             NOT NULL,
    per_ape_pat VARCHAR(100),
    per_ape_mat VARCHAR(100),
    per_tip_doc VARCHAR(10),
    per_num_doc VARCHAR(15),
    per_cor_ele VARCHAR(255),
    per_est     VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_personas PRIMARY KEY (per_cod)
);

CREATE TABLE sedes
(
    sed_cod     INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    usu_reg     INTEGER                                  NOT NULL,
    usu_mod     INTEGER                                  NOT NULL,
    fec_hor_reg TIMESTAMP with time zone                 NOT NULL,
    fec_hor_mod TIMESTAMP with time zone                 NOT NULL,
    sed_nom     VARCHAR(128)                             NOT NULL,
    sed_ubi_cod CHAR(6)                                  NOT NULL,
    sed_dir     VARCHAR(255)                             NOT NULL,
    sed_ruc     CHAR(11)                                 NOT NULL,
    sed_raz_soc VARCHAR(255)                             NOT NULL,
    sed_est     VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_sedes PRIMARY KEY (sed_cod)
);

CREATE TABLE ubigeo
(
    ubi_cod CHAR(6)     NOT NULL,
    ubi_dpt VARCHAR(32) NOT NULL,
    ubi_pro VARCHAR(32) NOT NULL,
    ubi_dis VARCHAR(32) NOT NULL,
    CONSTRAINT pk_ubigeo PRIMARY KEY (ubi_cod)
);

CREATE TABLE usuarios
(
    usu_cod      INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 4) NOT NULL,
    usu_reg      INTEGER                                  NOT NULL,
    usu_mod      INTEGER                                  NOT NULL,
    fec_hor_reg  TIMESTAMP with time zone                 NOT NULL,
    fec_hor_mod  TIMESTAMP with time zone                 NOT NULL,
    usu_per_cod  INTEGER                                  NOT NULL,
    usu_nom      VARCHAR(100)                             NOT NULL,
    usu_cor_ele  VARCHAR(255)                             NOT NULL,
    usu_con      VARCHAR(255)                             NOT NULL,
    usu_perf_cod INTEGER                                  NOT NULL,
    usu_sed_cod  INTEGER                                  NOT NULL,
    usu_est      VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (usu_cod)
);

ALTER TABLE cliente
    ADD CONSTRAINT uc_cliente_cli_per_cod UNIQUE (cli_per_cod);

ALTER TABLE perfiles
    ADD CONSTRAINT uc_perfiles_perf_nom UNIQUE (perf_nom);

ALTER TABLE personas
    ADD CONSTRAINT uc_personas_per_cor_ele UNIQUE (per_cor_ele),
    ADD CONSTRAINT uc_personas_per_num_doc UNIQUE (per_num_doc);

ALTER TABLE sedes
    ADD CONSTRAINT uc_sedes_sed_nom UNIQUE (sed_nom),
    ADD CONSTRAINT uc_sedes_sed_raz_soc UNIQUE (sed_raz_soc),
    ADD CONSTRAINT uc_sedes_sed_ruc UNIQUE (sed_ruc);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_usu_cor_ele UNIQUE (usu_cor_ele),
    ADD CONSTRAINT uc_usuarios_usu_nom UNIQUE (usu_nom),
    ADD CONSTRAINT uc_usuarios_usu_per_cod UNIQUE (usu_per_cod);

ALTER TABLE cliente
    ADD CONSTRAINT FK_CLIENTE_ON_CLI_PER_COD FOREIGN KEY (cli_per_cod) REFERENCES personas (per_cod),
    ADD CONSTRAINT FK_CLIENTE_ON_USU_MOD FOREIGN KEY (usu_mod) REFERENCES usuarios (usu_cod),
    ADD CONSTRAINT FK_CLIENTE_ON_USU_REG FOREIGN KEY (usu_reg) REFERENCES usuarios (usu_cod);

ALTER TABLE perfiles
    ADD CONSTRAINT FK_PERFILES_ON_USU_MOD FOREIGN KEY (usu_mod) REFERENCES usuarios (usu_cod),
    ADD CONSTRAINT FK_PERFILES_ON_USU_REG FOREIGN KEY (usu_reg) REFERENCES usuarios (usu_cod);

ALTER TABLE personas
    ADD CONSTRAINT FK_PERSONAS_ON_USU_MOD FOREIGN KEY (usu_mod) REFERENCES usuarios (usu_cod),
    ADD CONSTRAINT FK_PERSONAS_ON_USU_REG FOREIGN KEY (usu_reg) REFERENCES usuarios (usu_cod);

ALTER TABLE sedes
    ADD CONSTRAINT FK_SEDES_ON_SED_UBI_COD FOREIGN KEY (sed_ubi_cod) REFERENCES ubigeo (ubi_cod),
    ADD CONSTRAINT FK_SEDES_ON_USU_MOD FOREIGN KEY (usu_mod) REFERENCES usuarios (usu_cod),
    ADD CONSTRAINT FK_SEDES_ON_USU_REG FOREIGN KEY (usu_reg) REFERENCES usuarios (usu_cod);

ALTER TABLE usuarios
    ADD CONSTRAINT FK_USUARIOS_ON_USU_MOD FOREIGN KEY (usu_mod) REFERENCES usuarios (usu_cod),
    ADD CONSTRAINT FK_USUARIOS_ON_USU_PERF_COD FOREIGN KEY (usu_perf_cod) REFERENCES perfiles (perf_cod),
    ADD CONSTRAINT FK_USUARIOS_ON_USU_PER_COD FOREIGN KEY (usu_per_cod) REFERENCES personas (per_cod),
    ADD CONSTRAINT FK_USUARIOS_ON_USU_REG FOREIGN KEY (usu_reg) REFERENCES usuarios (usu_cod),
    ADD CONSTRAINT FK_USUARIOS_ON_USU_SED_COD FOREIGN KEY (usu_sed_cod) REFERENCES sedes (sed_cod);